server:
  port: 8083

spring:
  application:
    name: notificacao

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:teste@gmail.com}
    password: ${MAIL_PASSWORD:123456}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

jwt:
  secret: ${APP_JWT_SECRET:chave-super-secreta-minima-32-caracteres-para-HS512-2026}
  expiration-ms: 86400000